### ISSUE TITLE
My team

### ISSUE THREAD

**Issue by willsthewolf** [felixphew/pokepaste#21] opened 2017-09-05 11:54 UTC
Infernape @ Expert Belt  
Ability: Blaze  
EVs: 4 Def / 252 SpA / 252 Spe  
Timid Nature  
- Fire Blast  
- Vacuum Wave  
- Stealth Rock  
- Fake Out  

Scizor @ Scizorite  
Ability: Technician  
EVs: 252 HP / 252 SpD  
Careful Nature  
- Bullet Punch  
- Defog  
- U-turn  
- Roost  

Staraptor @ Choice Scarf  
Ability: Intimidate  
EVs: 252 Atk / 4 SpD / 252 Spe  
Jolly Nature  
- Brave Bird  
- Steel Wing  
- U-turn  
- Close Combat  

Cloyster @ Focus Sash  
Ability: Skill Link  
EVs: 252 Atk / 4 SpD / 252 Spe  
Adamant Nature  
- Icicle Spear  
- Rock Blast  
- Shell Smash  
- Ice Shard  

Vaporeon @ Leftovers  
Ability: Water Absorb  
EVs: 252 HP / 252 SpD  
Calm Nature  
IVs: 0 Atk  
- Scald  
- Wish  
- Protect  
- Toxic  

Trevenant @ Kee Berry  
Ability: Harvest  
EVs: 252 HP / 252 Def  
Impish Nature  
- Shadow Claw  
- Will-O-Wisp  
- Reflect  
- Leech Seed

**Comment by felixphew** [comment] 2017-09-05 21:58
@willsthewolf what exactly is the issue here? I can't see any problems with that team, it's pasting fine.

**Comment by felixphew** [comment] 2017-10-09 04:20
I'm going to close this issue. Feel free to re-open and explain what the problem is.

**Closed by felixphew** 2017-10-09 04:20 UTC
